---
  env:
    jest: true

  parser: babel-eslint

  parserOptions:
    ecmaVersion: 2017
    ecmaFeatures:
      jsx: true
    sourceType: module

  extends:
    - airbnb
    - plugin:flowtype/recommended

  plugins:
    - flowtype

  rules:
    comma-dangle:
      - error
      - arrays: always-multiline
        objects: always-multiline
        imports: always-multiline
        exports: always-multiline
        functions: only-multiline
    indent:
      - error
      - 4
    max-len:
      - error
      - 105
    no-use-before-define: 0
    no-param-reassign: 0
    react/jsx-indent:
      - error
      - 4
    react/jsx-indent-props:
      - error
      - 4
    react/jsx-filename-extension: 0
    flowtype/require-parameter-type:
      - error
      - { excludeArrowFunctions: true }
    flowtype/require-return-type:
      - error
    flowtype/require-valid-file-annotation:
      - error
      - always
    flowtype/space-after-type-colon:
      - warning
      - always
